---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: jaeger
spec:
  interval: 10m0s
  timeout: 10m0s
  chart:
    spec:
      chart: jaeger
      version: '3.3.1'
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: jaeger
      interval: 10m0s
  install:
    timeout: 10m0s
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    timeout: 10m0s
    remediation:
      retries: 3
      remediateLastFailure: true
    crds: CreateReplace
    cleanupOnFail: true
  uninstall:
    timeout: 5m
  driftDetection:
    mode: enabled
  values:
    # Deploy Jaeger all-in-one for simplicity
    allInOne:
      enabled: true
      image:
        registry: docker.io
        repository: jaegertracing/all-in-one
        tag: "1.52"
      # Expose Jaeger UI via NodePort
      service:
        type: NodePort
        nodePort: 30686
      
    # Storage configuration (in-memory for all-in-one)
    storage:
      type: memory
    
    # Disable cassandra (not needed for all-in-one)
    cassandra:
      enabled: false
    
    # Disable separate components (using all-in-one)
    agent:
      enabled: false
    collector:
      enabled: false
    query:
      enabled: false
